
[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.24.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

